name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches: [ master ]  # or "main" if that's your branch
  workflow_dispatch:  # allows manual deploy trigger
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy
        run: npm run build

      - name: Deploy to GitHub Pages v2
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
